name: node-package-helper-ci-cd

on: [push, pull_request]

jobs:
    all:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                node: [20]
                os: [ubuntu-latest, windows-latest]
                threads:
                    - '4'
        steps:
            - name: Checkout Code
            - uses: actions/checkout@v3

            - name: Install Node
            - uses: actions/setup-node@v3

            - name: Install Pnpm
              run: npm i --location=global pnpm

            - name: Install Depedencies
              run: pnpm i

            - name: Run Linter
              run: pnpm lint

            - name: Run Format Check
              run: pnpm format-check

            - name: Run Tests
              run: pnpm test

            - name: Run Build
              run: pnpm build
